language: php

php:
  - 5.5

env:
  global:
    - PHPBB_TAG="develop-olympus"
    - PHPBB_VERSION="3.0"
    - PHPBB_LANGUAGE="fr"

before_install:
 - sudo mkdir -p $PHPBB_VERSION/$PHPBB_LANGUAGE
 - sudo mkdir -p $PHPBB_VERSION/en/language
 - sudo mkdir -p $PHPBB_VERSION/en/styles/prosilver/theme
 - sudo mkdir -p $PHPBB_VERSION/en/styles/subsilver2/theme
 - sudo mv language $PHPBB_VERSION/$PHPBB_LANGUAGE
 - sudo mv styles $PHPBB_VERSION/$PHPBB_LANGUAGE
 - git clone --branch $PHPBB_TAG "https://github.com/phpbb/phpbb.git"
 - sudo mv phpbb/phpBB/language/en $PHPBB_VERSION/en/language
 - sudo mv phpbb/phpBB/styles/prosilver/theme/en $PHPBB_VERSION/en/styles/prosilver/theme
 - sudo mv phpbb/phpBB/styles/subsilver2/theme/en $PHPBB_VERSION/en/styles/subsilver2/theme
 - curl -sS "https://getcomposer.org/installer" | php

install:
 - php composer.phar install --dev --no-interaction --prefer-source

script:
  - php vendor/bin/PhpbbTranslationValidator.php validate $PHPBB_LANGUAGE --phpbb-version=$PHPBB_VERSION --display-notices
